server.port=8081
spring.application.name=GoogleTakeoutMetadataRestorer
logging.level.org.springframework.web=INFO

# Spring Boot DevTools & LiveReload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.web.resources.cache.period=0
