const REPO_OWNER = "Rahul-Jena-2002";
const REPO_NAME = "GooglePhotosTakeout";

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const path = url.pathname.toLowerCase();

    // Map download paths to expected file names (separate portable and installer packages)
    let targetFileName = "";
    if (path === "/download/windows/portable" || path === "/download/windows/zip") {
      targetFileName = "TakeoutFix-Windows-Portable.zip";
    } else if (path === "/download/windows" || path === "/download/windows/installer" || path === "/download/windows/msi") {
      targetFileName = "TakeoutFix-Setup.msi";
    } else if (path === "/download/macos/portable" || path === "/download/macos/zip") {
      targetFileName = "TakeoutFix-macOS-Portable.zip";
    } else if (path === "/download/macos" || path === "/download/macos/installer" || path === "/download/macos/dmg") {
      targetFileName = "TakeoutFix-macOS.dmg";
    } else if (path === "/download/linux/deb") {
      targetFileName = "TakeoutFix-Linux.deb";
    } else if (path === "/download/linux/rpm") {
      targetFileName = "TakeoutFix-Linux.rpm";
    } else if (path === "/download/linux/portable" || path === "/download/linux/tar") {
      targetFileName = "TakeoutFix-Linux-Portable.tar.gz";
    } else if (path === "/" || path === "/download") {
      return Response.redirect("https://takeoutfix.com/download", 302);
    } else {
      return new Response("Not Found. Available routes:\n- /download/windows/installer (MSI)\n- /download/windows/portable (.zip)\n- /download/macos/installer (.dmg)\n- /download/macos/portable (.zip)\n- /download/linux/deb (.deb)\n- /download/linux/rpm (.rpm)\n- /download/linux/portable (.tar.gz)", {
        status: 404,
        headers: { "Content-Type": "text/plain" }
      });
    }

    const token = env.GITHUB_PAT;
    if (!token) {
      return new Response(
        "Configuration Required: Missing GITHUB_PAT secret.\n\n" +
        `Because the GitHub repository '${REPO_OWNER}/${REPO_NAME}' is private, GitHub requires an authorized access token to download release assets.\n\n` +
        "To fix this:\n" +
        "1. Open Cloudflare Dashboard -> Workers & Pages -> takeoutfix-download -> Settings -> Variables and Secrets.\n" +
        "2. Add a secret named 'GITHUB_PAT' containing a GitHub token with 'Contents: Read-only' permission.",
        { status: 500, headers: { "Content-Type": "text/plain" } }
      );
    }

    try {
      // 1. Fetch latest release details from GitHub API
      const releaseUrl = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/releases/latest`;
      const releaseResponse = await fetch(releaseUrl, {
        headers: {
          "Authorization": `Bearer ${token}`,
          "User-Agent": "Cloudflare-Worker",
          "Accept": "application/vnd.github.v3+json"
        }
      });

      if (!releaseResponse.ok) {
        const errorText = await releaseResponse.text();
        return new Response(`Error fetching release from GitHub (${releaseResponse.status}): ${errorText}`, {
          status: releaseResponse.status,
          headers: { "Content-Type": "text/plain" }
        });
      }

      const releaseData = await releaseResponse.json();
      const assets = releaseData.assets || [];

      // 2. Find the asset matching our target file name, with smart fallback to portable archive
      let targetAsset = assets.find(asset => asset.name === targetFileName);
      if (!targetAsset) {
        if (targetFileName.toLowerCase().includes("windows")) {
          targetAsset = assets.find(asset => asset.name.toLowerCase().includes("windows"));
        } else if (targetFileName.toLowerCase().includes("macos")) {
          targetAsset = assets.find(asset => asset.name.toLowerCase().includes("macos"));
        } else if (targetFileName.toLowerCase().includes("linux")) {
          targetAsset = assets.find(asset => asset.name.toLowerCase().includes("linux"));
        }
      }

      if (!targetAsset) {
        return new Response(`File ${targetFileName} not found in the latest release (${releaseData.tag_name || 'latest'}). Available release assets: ${assets.map(a => a.name).join(', ')}`, {
          status: 404,
          headers: { "Content-Type": "text/plain" }
        });
      }

      // 3. Request the asset binary from GitHub
      const assetUrl = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/releases/assets/${targetAsset.id}`;
      const assetResponse = await fetch(assetUrl, {
        headers: {
          "Authorization": `Bearer ${token}`,
          "User-Agent": "Cloudflare-Worker",
          "Accept": "application/octet-stream"
        },
        redirect: "manual" // Stop automatic redirect follow to capture the S3 URL
      });

      // Capture the Location header (pre-signed S3 URL generated by GitHub) and redirect client directly
      const redirectUrl = assetResponse.headers.get("Location");
      if (assetResponse.status === 302 && redirectUrl) {
        return Response.redirect(redirectUrl, 302);
      }

      // If GitHub didn't return a redirect, try to stream the content directly
      return new Response(assetResponse.body, {
        status: assetResponse.status,
        headers: {
          "Content-Type": "application/octet-stream",
          "Content-Disposition": `attachment; filename="${targetFileName}"`
        }
      });

    } catch (err) {
      return new Response(`Internal Server Error: ${err.message}`, { status: 500 });
    }
  }
};
