const REPO_OWNER = "Rahul-Jena-2002";
const REPO_NAME = "GooglePhotosTakeout";

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const path = url.pathname.toLowerCase();

    // Map download paths to expected file names (Direct runnable Rust & Java editions)
    let targetFileName = "";
    if (path === "/download/windows/rust" || path === "/download/windows/exe" || path === "/download/windows") {
      targetFileName = "TakeoutFix.exe";
    } else if (path === "/download/windows/java" || path === "/download/windows/installer" || path === "/download/windows/msi") {
      targetFileName = "TakeoutFix-Java.exe";
    } else if (path === "/download/macos/rust" || path === "/download/macos/dmg" || path === "/download/macos") {
      targetFileName = "TakeoutFix.dmg";
    } else if (path === "/download/macos/java") {
      targetFileName = "TakeoutFix-Java.dmg";
    } else if (path === "/download/linux/rust" || path === "/download/linux/appimage" || path === "/download/linux") {
      targetFileName = "TakeoutFix.AppImage";
    } else if (path === "/download/linux/java") {
      targetFileName = "TakeoutFix-Java.AppImage";
    } else if (path === "/download/linux/deb") {
      targetFileName = "TakeoutFix-Linux.deb";
    } else if (path === "/download/linux/rpm") {
      targetFileName = "TakeoutFix-Linux.rpm";
    } else if (path === "/" || path === "/download") {
      return Response.redirect("https://takeoutfix.pages.dev/download", 302);
    } else {
      return new Response("Not Found. Available routes:\n- /download/windows/rust (TakeoutFix.exe)\n- /download/windows/java (TakeoutFix-Java.exe)\n- /download/macos/rust (TakeoutFix.dmg)\n- /download/macos/java (TakeoutFix-Java.dmg)\n- /download/linux/rust (TakeoutFix.AppImage)\n- /download/linux/java (TakeoutFix-Java.AppImage)", {
        status: 404,
        headers: { "Content-Type": "text/plain" }
      });
    }

    const headers = {
      "User-Agent": "Cloudflare-Worker",
      "Accept": "application/vnd.github.v3+json"
    };
    if (env.GITHUB_PAT) {
      headers["Authorization"] = `Bearer ${env.GITHUB_PAT}`;
    }

    try {
      // 1. Fetch latest release details from GitHub API
      const releaseUrl = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/releases/latest`;
      const releaseResponse = await fetch(releaseUrl, { headers });

      if (!releaseResponse.ok) {
        const errorText = await releaseResponse.text();
        return new Response(`Error fetching release from GitHub (${releaseResponse.status}): ${errorText}`, {
          status: releaseResponse.status,
          headers: { "Content-Type": "text/plain" }
        });
      }

      const releaseData = await releaseResponse.json();
      const assets = releaseData.assets || [];

      // 2. Find the exact asset matching the requested target file name (no mixing portable and installer)
      const targetAsset = assets.find(asset => asset.name.toLowerCase() === targetFileName.toLowerCase());

      if (!targetAsset) {
        return new Response(
          `The requested file '${targetFileName}' was not found in release '${releaseData.tag_name || 'latest'}'.\n\n` +
          `Available assets in this release:\n${assets.map(a => '- ' + a.name).join('\n')}`,
          {
            status: 404,
            headers: { "Content-Type": "text/plain" }
          }
        );
      }

      // 3. Request the asset binary from GitHub
      const assetUrl = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/releases/assets/${targetAsset.id}`;
      const assetHeaders = {
        "User-Agent": "Cloudflare-Worker",
        "Accept": "application/octet-stream"
      };
      if (env.GITHUB_PAT) {
        assetHeaders["Authorization"] = `Bearer ${env.GITHUB_PAT}`;
      }
      const assetResponse = await fetch(assetUrl, {
        headers: assetHeaders,
        redirect: "manual" // Stop automatic redirect follow to capture the S3 URL
      });

      // Capture the Location header (pre-signed S3 URL generated by GitHub) and redirect client directly
      const redirectUrl = assetResponse.headers.get("Location");
      if (assetResponse.status === 302 && redirectUrl) {
        return Response.redirect(redirectUrl, 302);
      }

      // If GitHub didn't return a redirect, try to stream the content directly
      return new Response(assetResponse.body, {
        status: assetResponse.status,
        headers: {
          "Content-Type": "application/octet-stream",
          "Content-Disposition": `attachment; filename="${targetFileName}"`
        }
      });

    } catch (err) {
      return new Response(`Internal Server Error: ${err.message}`, { status: 500 });
    }
  }
};
