import type {
  AdProvider,
  AdUnit,
  AffiliateProvider,
  AffiliateLink,
  MonetizationPlacement,
  MonetizationConfig,
  MonetizationGlobalSettings,
} from "./types";

export const DEFAULT_GLOBAL_SETTINGS: MonetizationGlobalSettings = {
  enabled: true,
  defaultMode: "BOTH",
  fallbackEnabled: true,
  allowPaidExemption: true,
  adOpacity: 80,
  adSize: "small",
  updatedAt: Date.now(),
};

export const DEFAULT_PLACEMENTS: MonetizationPlacement[] = [
  {
    id: "ARTICLE_TOP",
    code: "ARTICLE_TOP",
    name: "Article Top Banner",
    description: "Placed immediately beneath the article title and author bio.",
    status: "ACTIVE",
  },
  {
    id: "ARTICLE_MIDDLE",
    code: "ARTICLE_MIDDLE",
    name: "Article Middle Content",
    description: "Embedded halfway through guide articles and SEO walkthroughs.",
    status: "ACTIVE",
  },
  {
    id: "ARTICLE_BOTTOM",
    code: "ARTICLE_BOTTOM",
    name: "Article Bottom Footer",
    description: "Rendered below the article conclusion before related topics.",
    status: "ACTIVE",
  },
  {
    id: "SIDEBAR",
    code: "SIDEBAR",
    name: "Application & Workspace Sidebar",
    description: "Vertical slot inside navigation and tool side panels.",
    status: "ACTIVE",
  },
  {
    id: "SIDEBAR_LEFT_TOP",
    code: "SIDEBAR_LEFT_TOP",
    name: "Left Sidebar Top Slot",
    description: "Top placement in left gutter sidebar.",
    status: "ACTIVE",
  },
  {
    id: "SIDEBAR_LEFT_MID",
    code: "SIDEBAR_LEFT_MID",
    name: "Left Sidebar Mid Slot",
    description: "Middle placement in left gutter sidebar.",
    status: "ACTIVE",
  },
  {
    id: "SIDEBAR_LEFT_BOTTOM",
    code: "SIDEBAR_LEFT_BOTTOM",
    name: "Left Sidebar Bottom Slot",
    description: "Bottom placement in left gutter sidebar.",
    status: "ACTIVE",
  },
  {
    id: "SIDEBAR_RIGHT_TOP",
    code: "SIDEBAR_RIGHT_TOP",
    name: "Right Sidebar Top Slot",
    description: "Top placement in right gutter sidebar.",
    status: "ACTIVE",
  },
  {
    id: "SIDEBAR_RIGHT_MID",
    code: "SIDEBAR_RIGHT_MID",
    name: "Right Sidebar Mid Slot",
    description: "Middle placement in right gutter sidebar.",
    status: "ACTIVE",
  },
  {
    id: "SIDEBAR_RIGHT_BOTTOM",
    code: "SIDEBAR_RIGHT_BOTTOM",
    name: "Right Sidebar Bottom Slot",
    description: "Bottom placement in right gutter sidebar.",
    status: "ACTIVE",
  },
  {
    id: "GUTTER_LEFT",
    code: "GUTTER_LEFT",
    name: "Gutter Left Slot",
    description: "Left gutter fallback placement.",
    status: "ACTIVE",
  },
  {
    id: "GUTTER_RIGHT",
    code: "GUTTER_RIGHT",
    name: "Gutter Right Slot",
    description: "Right gutter fallback placement.",
    status: "ACTIVE",
  },
  {
    id: "HOMEPAGE_TOP",
    code: "HOMEPAGE_TOP",
    name: "Homepage Header Slot",
    description: "Featured right after hero comparison section.",
    status: "ACTIVE",
  },
  {
    id: "HOMEPAGE_MIDDLE",
    code: "HOMEPAGE_MIDDLE",
    name: "Homepage Mid Banner",
    description: "Between feature breakdown and benchmark tables.",
    status: "ACTIVE",
  },
  {
    id: "HOMEPAGE_BOTTOM",
    code: "HOMEPAGE_BOTTOM",
    name: "Homepage Pre-Footer",
    description: "Placed before FAQ and testimonials.",
    status: "ACTIVE",
  },
  {
    id: "TOOL_BOTTOM",
    code: "TOOL_BOTTOM",
    name: "Tool Console Bottom Bar",
    description: "Non-intrusive sponsor unit inside tool execution screen.",
    status: "ACTIVE",
  },
  {
    id: "DOWNLOAD_TOP",
    code: "DOWNLOAD_TOP",
    name: "Download Page Action Slot",
    description: "Compact sponsor unit placed immediately below the download action button.",
    status: "ACTIVE",
  },
  {
    id: "DOWNLOAD_BOTTOM",
    code: "DOWNLOAD_BOTTOM",
    name: "Download Page System Specs Slot",
    description: "Compact sponsor unit placed below the hardware and system specifications.",
    status: "ACTIVE",
  },
];

export const DEFAULT_CONFIGS: Record<string, MonetizationConfig> = {
  ARTICLE_TOP: {
    id: "ARTICLE_TOP",
    placementCode: "ARTICLE_TOP",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  ARTICLE_MIDDLE: {
    id: "ARTICLE_MIDDLE",
    placementCode: "ARTICLE_MIDDLE",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  ARTICLE_BOTTOM: {
    id: "ARTICLE_BOTTOM",
    placementCode: "ARTICLE_BOTTOM",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  SIDEBAR: {
    id: "SIDEBAR",
    placementCode: "SIDEBAR",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  SIDEBAR_LEFT_TOP: {
    id: "SIDEBAR_LEFT_TOP",
    placementCode: "SIDEBAR_LEFT_TOP",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  SIDEBAR_LEFT_MID: {
    id: "SIDEBAR_LEFT_MID",
    placementCode: "SIDEBAR_LEFT_MID",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  SIDEBAR_LEFT_BOTTOM: {
    id: "SIDEBAR_LEFT_BOTTOM",
    placementCode: "SIDEBAR_LEFT_BOTTOM",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  SIDEBAR_RIGHT_TOP: {
    id: "SIDEBAR_RIGHT_TOP",
    placementCode: "SIDEBAR_RIGHT_TOP",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  SIDEBAR_RIGHT_MID: {
    id: "SIDEBAR_RIGHT_MID",
    placementCode: "SIDEBAR_RIGHT_MID",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  SIDEBAR_RIGHT_BOTTOM: {
    id: "SIDEBAR_RIGHT_BOTTOM",
    placementCode: "SIDEBAR_RIGHT_BOTTOM",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  GUTTER_LEFT: {
    id: "GUTTER_LEFT",
    placementCode: "GUTTER_LEFT",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  GUTTER_RIGHT: {
    id: "GUTTER_RIGHT",
    placementCode: "GUTTER_RIGHT",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  HOMEPAGE_TOP: {
    id: "HOMEPAGE_TOP",
    placementCode: "HOMEPAGE_TOP",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  HOMEPAGE_MIDDLE: {
    id: "HOMEPAGE_MIDDLE",
    placementCode: "HOMEPAGE_MIDDLE",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  HOMEPAGE_BOTTOM: {
    id: "HOMEPAGE_BOTTOM",
    placementCode: "HOMEPAGE_BOTTOM",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  TOOL_BOTTOM: {
    id: "TOOL_BOTTOM",
    placementCode: "TOOL_BOTTOM",
    displayMode: "AFFILIATE_ONLY",
    affiliatePercentage: 100,
    adsPercentage: 0,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  DOWNLOAD_TOP: {
    id: "DOWNLOAD_TOP",
    placementCode: "DOWNLOAD_TOP",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
  DOWNLOAD_BOTTOM: {
    id: "DOWNLOAD_BOTTOM",
    placementCode: "DOWNLOAD_BOTTOM",
    displayMode: "BOTH",
    affiliatePercentage: 50,
    adsPercentage: 50,
    fallbackEnabled: true,
    affiliateEnabled: true,
    adsEnabled: true,
    status: "ACTIVE",
  },
};

export const DEFAULT_AFFILIATE_PROVIDERS: AffiliateProvider[] = [
  {
    id: "aff_prov_amazon",
    name: "Amazon Associates",
    code: "AMAZON",
    status: "ACTIVE",
    tag: "rjtools-21",
  },
];

export const DEFAULT_AD_PROVIDERS: AdProvider[] = [
  {
    id: "ad_prov_google",
    name: "Google AdSense",
    code: "GOOGLE_ADSENSE",
    status: "ACTIVE",
    notes: "Automated Google AdSense responsive units.",
  },
  {
    id: "ad_prov_media_net",
    name: "Media.net Contextual Ads",
    code: "MEDIA_NET",
    status: "INACTIVE",
    notes: "Contextual advertisements network.",
  },
];

export const DEFAULT_AFFILIATE_LINKS: AffiliateLink[] = [
  {
    id: "aff_link_1",
    providerId: "aff_prov_amazon",
    providerName: "Amazon Associates",
    tag: "Audio & Acoustics",
    title: "Sony WF-1000XM5 Noise-Cancelling Earbuds",
    description: "Industry-leading active noise cancellation with dual processors & high-res LDAC audio.",
    destinationUrl: "https://link.amazon/B0fvI8kmw",
    ctaText: "Shop on Amazon",
    status: "ACTIVE",
    priority: 10,
    placementCodes: ["ARTICLE_TOP", "ARTICLE_MIDDLE", "ARTICLE_BOTTOM", "HOMEPAGE_TOP", "SIDEBAR"],
    isExternal: true,
  },
  {
    id: "aff_link_2",
    providerId: "aff_prov_amazon",
    providerName: "Amazon Associates",
    tag: "Mega Deals",
    title: "TCL 4K Smart TVs & QLED Home Theater",
    description: "Ultra HD 4K, Dolby Vision & Atmos Smart Google TVs at festival discount prices.",
    destinationUrl: "https://www.amazon.in/l/90035945031?tag=rjtools-21",
    ctaText: "View on Amazon",
    status: "ACTIVE",
    priority: 8,
    placementCodes: ["ARTICLE_MIDDLE", "HOMEPAGE_MIDDLE", "HOMEPAGE_BOTTOM"],
    isExternal: true,
  },
  {
    id: "aff_link_3",
    providerId: "aff_prov_amazon",
    providerName: "Amazon Associates",
    tag: "Mobile Gear",
    title: "URBN Compact Fast-Charging Power Bank",
    description: "Pocket-sized 20W/22.5W two-way Type-C fast-charging power bank for all smartphones.",
    destinationUrl: "https://link.amazon/B01sl4CAl",
    ctaText: "View on Amazon",
    status: "ACTIVE",
    priority: 7,
    placementCodes: ["ARTICLE_TOP", "ARTICLE_MIDDLE", "SIDEBAR", "HOMEPAGE_TOP"],
    isExternal: true,
  },
  {
    id: "aff_link_4",
    providerId: "aff_prov_amazon",
    providerName: "Amazon Associates",
    tag: "PC Accessories",
    title: "URBN Type-C Multi-Port Hub & Display Adapter",
    description: "High-speed Type-C hub with 4K HDMI, USB 3.0 ports, and fast Power Delivery pass-through.",
    destinationUrl: "https://link.amazon/B06mCC0hf",
    ctaText: "View on Amazon",
    status: "ACTIVE",
    priority: 6,
    placementCodes: ["ARTICLE_MIDDLE", "ARTICLE_BOTTOM", "SIDEBAR", "TOOL_BOTTOM"],
    isExternal: true,
  },
  {
    id: "aff_link_5",
    providerId: "aff_prov_amazon",
    providerName: "Amazon Associates",
    tag: "Desk Setup",
    title: "AGARO 3-in-1 Fast Wireless Charging Station",
    description: "Clean desktop charging dock for iPhone / Android, smartwatch, and AirPods simultaneously.",
    destinationUrl: "https://link.amazon/B0dwsdmBA",
    ctaText: "Shop Now",
    status: "ACTIVE",
    priority: 5,
    placementCodes: ["ARTICLE_MIDDLE", "HOMEPAGE_BOTTOM", "SIDEBAR"],
    isExternal: true,
  },
];

export const DEFAULT_AD_UNITS: AdUnit[] = [
  {
    id: "ad_unit_adsense_auto",
    providerId: "ad_prov_google",
    providerName: "Google AdSense",
    name: "AdSense Auto / Responsive Unit",
    adType: "HTML",
    embedCode: `<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-7628736172233995" data-ad-slot="auto" data-ad-format="auto" data-full-width-responsive="true"></ins>`,
    status: "ACTIVE",
    priority: 10,
    placementCodes: ["ARTICLE_TOP", "ARTICLE_MIDDLE", "ARTICLE_BOTTOM", "HOMEPAGE_TOP", "HOMEPAGE_MIDDLE", "HOMEPAGE_BOTTOM", "SIDEBAR", "TOOL_BOTTOM"],
  },
];

